In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [13]:
df=pd.read_excel("data/E Commerce Dataset.xlsx",sheet_name="E Comm")
data_dict=pd.read_excel("data/E Commerce Dataset.xlsx",sheet_name="Data Dict")

In [14]:
print(data_dict.to_string())

    Unnamed: 0 Unnamed: 1                   Unnamed: 2                                                     Unnamed: 3
0          NaN       Data                     Variable                                                    Discerption
1          NaN     E Comm                   CustomerID                                             Unique customer ID
2          NaN     E Comm                        Churn                                                     Churn Flag
3          NaN     E Comm                       Tenure                             Tenure of customer in organization
4          NaN     E Comm         PreferredLoginDevice                             Preferred login device of customer
5          NaN     E Comm                     CityTier                                                      City tier
6          NaN     E Comm              WarehouseToHome              Distance in between warehouse to home of customer
7          NaN     E Comm         PreferredPaymentMode                           Preferred payment method of customer
8          NaN     E Comm                       Gender                                             Gender of customer
9          NaN     E Comm               HourSpendOnApp         Number of hours spend on mobile application or website
10         NaN     E Comm     NumberOfDeviceRegistered  Total number of deceives is registered on particular customer
11         NaN     E Comm             PreferedOrderCat             Preferred order category of customer in last month
12         NaN     E Comm            SatisfactionScore                      Satisfactory score of customer on service
13         NaN     E Comm                MaritalStatus                                     Marital status of customer
14         NaN     E Comm              NumberOfAddress             Total number of added added on particular customer
15         NaN     E Comm                     Complain                    Any complaint has been raised in last month
16         NaN     E Comm  OrderAmountHikeFromlastYear                   Percentage increases in order from last year
17         NaN     E Comm                   CouponUsed             Total number of coupon has been used in last month
18         NaN     E Comm                   OrderCount           Total number of orders has been places in last month
19         NaN     E Comm            DaySinceLastOrder                               Day Since last order by customer
20         NaN     E Comm               CashbackAmount                                 Average cashback in last month

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5630 entries, 0 to 5629
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   CustomerID                   5630 non-null   int64
 1   Churn                        5630 non-null   int64
 2   Tenure                       5366 non-null   float64
 3   PreferredLoginDevice         5630 non-null   str
 4   CityTier                     5630 non-null   int64
 5   WarehouseToHome              5379 non-null   float64
 6   PreferredPaymentMode         5630 non-null   str
 7   Gender                       5630 non-null   str
 8   HourSpendOnApp               5375 non-null   float64
 9   NumberOfDeviceRegistered     5630 non-null   int64
 10  PreferedOrderCat             5630 non-null   str
 11  SatisfactionScore            5630 non-null   int64
 12  MaritalStatus                5630 non-null   str
 13  NumberOfAddress              5630 non-null   int64
 14  Complain                     5630 non-null   int64
 15  OrderAmountHikeFromlastYear  5365 non-null   float64
 16  CouponUsed                   5374 non-null   float64
 17  OrderCount                   5372 non-null   float64
 18  DaySinceLastOrder            5323 non-null   float64
 19  CashbackAmount               5630 non-null   float64
dtypes: float64(8), int64(7), str(5)
memory usage: 879.8 KB

In [16]:
df.describe()

,CustomerID,Churn,Tenure,CityTier,WarehouseToHome,HourSpendOnApp,NumberOfDeviceRegistered,SatisfactionScore,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
count,5630.000000,5630.000000,5366.000000,5630.000000,5379.000000,5375.000000,5630.000000,5630.000000,5630.000000,5630.000000,5365.000000,5374.000000,5372.000000,5323.000000,5630.000000
mean,52815.500000,0.168384,10.189899,1.654707,15.639896,2.931535,3.688988,3.066785,4.214032,0.284902,15.707922,1.751023,3.008004,4.543491,177.223030
std,1625.385339,0.374240,8.557241,0.915389,8.531475,0.721926,1.023999,1.380194,2.583586,0.451408,3.675485,1.894621,2.939680,3.654433,49.207036
min,50001.000000,0.000000,0.000000,1.000000,5.000000,0.000000,1.000000,1.000000,1.000000,0.000000,11.000000,0.000000,1.000000,0.000000,0.000000
25%,51408.250000,0.000000,2.000000,1.000000,9.000000,2.000000,3.000000,2.000000,2.000000,0.000000,13.000000,1.000000,1.000000,2.000000,145.770000
50%,52815.500000,0.000000,9.000000,1.000000,14.000000,3.000000,4.000000,3.000000,3.000000,0.000000,15.000000,1.000000,2.000000,3.000000,163.280000
75%,54222.750000,0.000000,16.000000,3.000000,20.000000,3.000000,4.000000,4.000000,6.000000,1.000000,18.000000,2.000000,3.000000,7.000000,196.392500
max,55630.000000,1.000000,61.000000,3.000000,127.000000,5.000000,6.000000,5.000000,22.000000,1.000000,26.000000,16.000000,16.000000,46.000000,324.990000

In [17]:
df.shape

(5630, 20)

In [18]:
df.head()

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
0,50001,1,4.0,Mobile Phone,3,6.0,Debit Card,Female,3.0,3,Laptop & Accessory,2,Single,9,1,11.0,1.0,1.0,5.0,159.93
1,50002,1,NaN,Phone,1,8.0,UPI,Male,3.0,4,Mobile,3,Single,7,1,15.0,0.0,1.0,0.0,120.90
2,50003,1,NaN,Phone,1,30.0,Debit Card,Male,2.0,4,Mobile,3,Single,6,1,14.0,0.0,1.0,3.0,120.28
3,50004,1,0.0,Phone,3,15.0,Debit Card,Male,2.0,4,Laptop & Accessory,5,Single,8,0,23.0,0.0,1.0,3.0,134.07
4,50005,1,0.0,Phone,1,12.0,CC,Male,NaN,3,Mobile,5,Single,3,0,11.0,1.0,1.0,3.0,129.60

In [19]:
df.sample(5)

,CustomerID,Churn,Tenure,PreferredLoginDevice,CityTier,WarehouseToHome,PreferredPaymentMode,Gender,HourSpendOnApp,NumberOfDeviceRegistered,PreferedOrderCat,SatisfactionScore,MaritalStatus,NumberOfAddress,Complain,OrderAmountHikeFromlastYear,CouponUsed,OrderCount,DaySinceLastOrder,CashbackAmount
3271,53272,0,4.0,Mobile Phone,1,7.0,Debit Card,Male,3.0,6,Mobile Phone,3,Divorced,5,0,22.0,2.0,2.0,3.0,163.33
5188,55189,0,15.0,Phone,1,12.0,Credit Card,Male,3.0,2,Mobile Phone,3,Married,4,1,13.0,1.0,2.0,4.0,146.27
2609,52610,0,28.0,Mobile Phone,1,8.0,Credit Card,Male,2.0,4,Others,5,Married,9,0,12.0,NaN,1.0,0.0,290.38
3015,53016,0,5.0,Computer,1,14.0,Debit Card,Female,3.0,5,Fashion,3,Divorced,3,0,25.0,4.0,9.0,NaN,214.43
1497,51498,0,NaN,Phone,3,12.0,E wallet,Male,2.0,3,Laptop & Accessory,3,Married,3,1,20.0,0.0,4.0,5.0,123.06

In [20]:
print(df.isnull().sum())
print(df.isnull().any(axis=1).sum())
print(df.notnull().all(axis=1).sum())

CustomerID                       0
Churn                            0
Tenure                         264
PreferredLoginDevice             0
CityTier                         0
WarehouseToHome                251
PreferredPaymentMode             0
Gender                           0
HourSpendOnApp                 255
NumberOfDeviceRegistered         0
PreferedOrderCat                 0
SatisfactionScore                0
MaritalStatus                    0
NumberOfAddress                  0
Complain                         0
OrderAmountHikeFromlastYear    265
CouponUsed                     256
OrderCount                     258
DaySinceLastOrder              307
CashbackAmount                   0
dtype: int64
1856
3774

In [21]:
df['Churn'].value_counts(normalize=True)

Churn
0    0.831616
1    0.168384
Name: proportion, dtype: float64

In [22]:
df[df.duplicated()]

Empty DataFrame
Columns: [CustomerID, Churn, Tenure, PreferredLoginDevice, CityTier, WarehouseToHome, PreferredPaymentMode, Gender, HourSpendOnApp, NumberOfDeviceRegistered, PreferedOrderCat, SatisfactionScore, MaritalStatus, NumberOfAddress, Complain, OrderAmountHikeFromlastYear, CouponUsed, OrderCount, DaySinceLastOrder, CashbackAmount]
Index: []