In [142]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

In [143]:
df=pd.read_excel("data/E Commerce Dataset.xlsx",sheet_name="E Comm")
data_dict=pd.read_excel("data/E Commerce Dataset.xlsx",sheet_name="Data Dict")

In [144]:
df_numeric=df.select_dtypes(include=['number']).columns.to_list()
df_categorical=df.select_dtypes(include=['str']).columns.to_list()

In [145]:
df_numeric
df_categorical

['PreferredLoginDevice',
 'PreferredPaymentMode',
 'Gender',
 'PreferedOrderCat',
 'MaritalStatus']

In [146]:
for col in df_numeric:
    if df[col].isnull().sum() > 0:
        df[f'{col}_is_missing'] = df[col].isnull().astype(int)
        median_value = df[col].median()
        df[col] = df[col].fillna(median_value)

In [147]:
df.isnull().sum()

CustomerID                                0
Churn                                     0
Tenure                                    0
PreferredLoginDevice                      0
CityTier                                  0
WarehouseToHome                           0
PreferredPaymentMode                      0
Gender                                    0
HourSpendOnApp                            0
NumberOfDeviceRegistered                  0
PreferedOrderCat                          0
SatisfactionScore                         0
MaritalStatus                             0
NumberOfAddress                           0
Complain                                  0
OrderAmountHikeFromlastYear               0
CouponUsed                                0
OrderCount                                0
DaySinceLastOrder                         0
CashbackAmount                            0
Tenure_is_missing                         0
WarehouseToHome_is_missing                0
HourSpendOnApp_is_missing                 0
OrderAmountHikeFromlastYear_is_missing    0
CouponUsed_is_missing                     0
OrderCount_is_missing                     0
DaySinceLastOrder_is_missing              0
dtype: int64

In [148]:
for col in df_categorical:
    uniques=df[col].unique()
    print(f'{col} ({len(uniques)} unique values):\n  {uniques}\n')

PreferredLoginDevice (3 unique values):
  <StringArray>
['Mobile Phone', 'Phone', 'Computer']
Length: 3, dtype: str

PreferredPaymentMode (7 unique values):
  <StringArray>
['Debit Card', 'UPI', 'CC', 'Cash on Delivery', 'E wallet', 'COD',
 'Credit Card']
Length: 7, dtype: str

Gender (2 unique values):
  <StringArray>
['Female', 'Male']
Length: 2, dtype: str

PreferedOrderCat (6 unique values):
  <StringArray>
['Laptop & Accessory', 'Mobile', 'Mobile Phone', 'Others', 'Fashion',
 'Grocery']
Length: 6, dtype: str

MaritalStatus (3 unique values):
  <StringArray>
['Single', 'Divorced', 'Married']
Length: 3, dtype: str

In [149]:
df['PreferredLoginDevice']=df['PreferredLoginDevice'].str.replace('Mobile Phone','Phone',regex=False)
df['PreferredPaymentMode']=df['PreferredPaymentMode'].str.replace('Credit Card','CC',regex=False)
df['PreferredPaymentMode']=df['PreferredPaymentMode'].str.replace('Cash on Delivery','COD',regex=False)
df['PreferedOrderCat']=df['PreferedOrderCat'].str.replace('Mobile Phone','Phone',regex=False)

In [150]:
df[['PreferredLoginDevice','PreferredPaymentMode','Gender','PreferedOrderCat','MaritalStatus']]

,PreferredLoginDevice,PreferredPaymentMode,Gender,PreferedOrderCat,MaritalStatus
0,Phone,Debit Card,Female,Laptop & Accessory,Single
1,Phone,UPI,Male,Mobile,Single
2,Phone,Debit Card,Male,Mobile,Single
3,Phone,Debit Card,Male,Laptop & Accessory,Single
4,Phone,CC,Male,Mobile,Single
...,...,...,...,...,...
5625,Computer,CC,Male,Laptop & Accessory,Married
5626,Phone,CC,Male,Fashion,Married
5627,Phone,Debit Card,Male,Laptop & Accessory,Married
5628,Computer,CC,Male,Laptop & Accessory,Married
5629,Phone,CC,Male,Laptop & Accessory,Married

In [151]:
encoder=OneHotEncoder(sparse_output=False,drop='first')
encoded_list=encoder.fit_transform(df[df_categorical])
encoded_df = pd.DataFrame(encoded_list, 
                          columns=encoder.get_feature_names_out(df_categorical))

df=pd.concat([df,encoded_df],axis=1)
df = df.drop(columns=df_categorical)

In [152]:
df

,CustomerID,Churn,Tenure,CityTier,WarehouseToHome,HourSpendOnApp,NumberOfDeviceRegistered,SatisfactionScore,NumberOfAddress,Complain,...,PreferredPaymentMode_E wallet,PreferredPaymentMode_UPI,Gender_Male,PreferedOrderCat_Grocery,PreferedOrderCat_Laptop & Accessory,PreferedOrderCat_Mobile,PreferedOrderCat_Others,PreferedOrderCat_Phone,MaritalStatus_Married,MaritalStatus_Single
0,50001,1,4.0,3,6.0,3.0,3,2,9,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,50002,1,9.0,1,8.0,3.0,4,3,7,1,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,50003,1,9.0,1,30.0,2.0,4,3,6,1,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,50004,1,0.0,3,15.0,2.0,4,5,8,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,50005,1,0.0,1,12.0,3.0,3,5,3,0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,55626,0,10.0,1,30.0,3.0,2,1,6,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5626,55627,0,13.0,1,13.0,3.0,5,5,6,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5627,55628,0,1.0,1,11.0,3.0,2,4,3,1,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5628,55629,0,23.0,3,9.0,4.0,5,4,4,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
5629,55630,0,8.0,1,15.0,3.0,2,3,4,0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [153]:
df.to_csv("data/E_Commerce_Cleaned.csv", index=False)